RUN_NAME: 'PGN'
ALGORITHM: 'bfs'
MODEL:
  DECODER_USE_LAST_HIDDEN: True
  PROCESSOR_USE_LAST_HIDDEN: True
  PROCESSOR:
    NAME: "PGN"
    RESIDUAL: False
    KWARGS: [{"aggr": "max"}]
    LAYERNORM:
      ENABLE: True
      MODE: "node"
  LATENT_NOISE_STD: 0.015  # σ for Gaussian noise injected into hidden state during training
  TEACHER_FORCING:
    ENABLE: True
    HINT_DROPOUT: 0.2
  AUTOREGRESSIVE:
    ENABLE: True
  GRU:
    ENABLE: True

DATA:
  TRAIN:
    NUM_SAMPLES: [3334, 3333, 3333]
    GRAPH_GENERATOR: ["er", "ws", "delaunay"]
    GENERATOR_PARAMS: 
      - { "n": [4, 7, 11, 13, 16], "p_range": [0.17, 0.52] }
      - { "n": [11, 13, 16, 20], "p_range": [0.05, 0.2], "k": [4,6,8] }
      - { "n": [4, 7, 11, 13, 16] }
  VAL:
    NUM_SAMPLES: 5
    GRAPH_GENERATOR: ["er", "er", "er", "ws", "ws", "ws", "delaunay", "delaunay", "delaunay"]
    NICKNAME: ["er_16", "er_80", "er_800", "ws_16", "ws_80", "ws_800", "delaunay_16", "delaunay_80", "delaunay_800"]
    GENERATOR_PARAMS: 
      - { "p_range": [0.173, 0.52], "n": 16 }
      - { "p_range": [0.054, 0.164], "n": 80 }
      - { "p_range": [0.008, 0.025], "n": 800 }
      - { "p_range": [0.05, 0.2], "k": [4,6,8], "n": 16 }
      - { "p_range": [0.05, 0.2], "k": [4,6,8], "n": 80 }
      - { "p_range": [0.05, 0.2], "k": [4,6,8], "n": 800 }
      - { "n": 16 }
      - { "n": 80 }
      - { "n": 800 }
  TEST:
    NUM_SAMPLES: 5
    GRAPH_GENERATOR: ["er", "er", "er", "ws", "ws", "ws", "delaunay", "delaunay", "delaunay"]
    NICKNAME: ["er_16", "er_80", "er_800", "ws_16", "ws_80", "ws_800", "delaunay_16", "delaunay_80", "delaunay_800"]
    GENERATOR_PARAMS:
      - { "p_range": [0.173, 0.52], "n": 16 }
      - { "p_range": [0.054, 0.164], "n": 80 }
      - { "p_range": [0.008, 0.025], "n": 800 }
      - { "p_range": [0.05, 0.2], "k": [4,6,8], "n": 16 }
      - { "p_range": [0.05, 0.2], "k": [4,6,8], "n": 80 }
      - { "p_range": [0.05, 0.2], "k": [4,6,8], "n": 800 }
      - { "n": 16 }
      - { "n": 80 }
      - { "n": 800 }

TRAIN:
  GRADIENT_CLIP_VAL: 0.5
  LOSS:
    OUTPUT_LOSS_WEIGHT: 1.0
    HINT_LOSS_WEIGHT: 1.0
    HIDDEN_LOSS_WEIGHT: 0.0 # disabled for grokking (and because of GRU and LayerNorm)
  MAX_EPOCHS: 2000 # Increased for grokking
  BATCH_SIZE: 256

  ENABLE: True
  NUM_WORKERS: 16
  EARLY_STOPPING_PATIENCE: 2000 # Effectively disabled
  OPTIMIZER:
    LR: 0.0004239
    WEIGHT_DECAY: 0.1 # higher for grokking

  SCHEDULER:
    ENABLE: False # disabled for grokking
    NAME: "ReduceLROnPlateau"
    PARAMS: [{ "mode": "min", "factor": 0.5, "patience": 50 }] 

TEST:
  BATCH_SIZE: 8

LOGGING:
  WANDB:
    PROJECT: "nar-experiments"
    GROUP: "PGN"
